language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

services:
  - mysql
  
before_install:
  - mysql < tests/db-class-testing.sql
  
install:
  - if [[ ${TRAVIS_PHP_VERSION} >= "7.1" ]]; then composer install; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "7.0" ]]; then composer require --dev phpunit/phpunit ^6 phpunit/dbunit ^3; fi
  
script:
  - ./vendor/bin/phpunit --configuration phpunit.travis.xml
